/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.cadastro;

import controller.ProfissionalController;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Tiago e Diogo
 */
public class viewProfissional extends javax.swing.JFrame {

    private final ProfissionalController controller;

    public viewProfissional() {
        initComponents();
        controller = new ProfissionalController(this);
        controller.carregarProfissionais();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TxtId = new javax.swing.JTextField();
        lblid = new javax.swing.JLabel();
        TxtNome = new javax.swing.JTextField();
        lblnome = new javax.swing.JLabel();
        TxtRg = new javax.swing.JTextField();
        lblcpf = new javax.swing.JLabel();
        TxtPesquisa = new javax.swing.JTextField();
        TxtCpf = new javax.swing.JTextField();
        TxtEmail = new javax.swing.JTextField();
        lblemail = new javax.swing.JLabel();
        lblclientes = new javax.swing.JLabel();
        lblcpf1 = new javax.swing.JLabel();
        lblemail1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TabelaProfissionais = new javax.swing.JTable();
        lbltelefone1 = new javax.swing.JLabel();
        TxtTelefone = new javax.swing.JTextField();
        BtnUltimo = new javax.swing.JButton();
        BtnAnterior = new javax.swing.JButton();
        BtnProximo = new javax.swing.JButton();
        BtnPrimeiro = new javax.swing.JButton();
        btndeletar = new javax.swing.JButton();
        btnalterar = new javax.swing.JButton();
        btnagendar = new javax.swing.JButton();
        lblpainel = new javax.swing.JLabel();
        lblfundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TxtId.setEditable(false);
        TxtId.setEnabled(false);
        TxtId.setFocusable(false);
        getContentPane().add(TxtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 40, -1));

        lblid.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblid.setForeground(new java.awt.Color(204, 204, 204));
        lblid.setText("Id");
        getContentPane().add(lblid, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, -1, -1));

        TxtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNomeActionPerformed(evt);
            }
        });
        getContentPane().add(TxtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 192, 30));

        lblnome.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblnome.setForeground(new java.awt.Color(204, 204, 204));
        lblnome.setText("Nome");
        getContentPane().add(lblnome, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, -1, -1));
        getContentPane().add(TxtRg, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 192, 30));

        lblcpf.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblcpf.setForeground(new java.awt.Color(204, 204, 204));
        lblcpf.setText("RG");
        getContentPane().add(lblcpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, -1, -1));

        TxtPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtPesquisaKeyReleased(evt);
            }
        });
        getContentPane().add(TxtPesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, 240, -1));
        getContentPane().add(TxtCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 192, 30));
        getContentPane().add(TxtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 192, -1));

        lblemail.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblemail.setForeground(new java.awt.Color(204, 204, 204));
        lblemail.setText("Pesquisar Profissional:");
        getContentPane().add(lblemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, -1, 20));

        lblclientes.setFont(new java.awt.Font("Arial", 1, 28)); // NOI18N
        lblclientes.setForeground(new java.awt.Color(204, 204, 204));
        lblclientes.setText("Profissionais");
        getContentPane().add(lblclientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, -1, -1));

        lblcpf1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblcpf1.setForeground(new java.awt.Color(204, 204, 204));
        lblcpf1.setText("CPF");
        getContentPane().add(lblcpf1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, -1, -1));

        lblemail1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblemail1.setForeground(new java.awt.Color(204, 204, 204));
        lblemail1.setText("Email");
        getContentPane().add(lblemail1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, -1, -1));

        TabelaProfissionais.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nome", "CPF", "RG", "Telefone", "Email"
            }
        ));
        TabelaProfissionais.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaProfissionaisMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TabelaProfissionais);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, 670, 120));

        lbltelefone1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbltelefone1.setForeground(new java.awt.Color(204, 204, 204));
        lbltelefone1.setText("Telefone");
        getContentPane().add(lbltelefone1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, -1, -1));
        getContentPane().add(TxtTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 192, 30));

        BtnUltimo.setBackground(new java.awt.Color(44, 148, 82));
        BtnUltimo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        BtnUltimo.setForeground(new java.awt.Color(255, 255, 255));
        BtnUltimo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imgBarb/icons/final.png"))); // NOI18N
        BtnUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUltimoActionPerformed(evt);
            }
        });
        getContentPane().add(BtnUltimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 280, 30, 30));

        BtnAnterior.setBackground(new java.awt.Color(44, 148, 82));
        BtnAnterior.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        BtnAnterior.setForeground(new java.awt.Color(255, 255, 255));
        BtnAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imgBarb/icons/anterior.png"))); // NOI18N
        BtnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAnteriorActionPerformed(evt);
            }
        });
        getContentPane().add(BtnAnterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 280, 30, 30));

        BtnProximo.setBackground(new java.awt.Color(44, 148, 82));
        BtnProximo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        BtnProximo.setForeground(new java.awt.Color(255, 255, 255));
        BtnProximo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imgBarb/icons/proximo.png"))); // NOI18N
        BtnProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnProximoActionPerformed(evt);
            }
        });
        getContentPane().add(BtnProximo, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 280, 30, 30));

        BtnPrimeiro.setBackground(new java.awt.Color(44, 148, 82));
        BtnPrimeiro.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        BtnPrimeiro.setForeground(new java.awt.Color(255, 255, 255));
        BtnPrimeiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imgBarb/icons/inicio.png"))); // NOI18N
        BtnPrimeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPrimeiroActionPerformed(evt);
            }
        });
        getContentPane().add(BtnPrimeiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 280, 30, 30));

        btndeletar.setBackground(new java.awt.Color(44, 148, 82));
        btndeletar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btndeletar.setForeground(new java.awt.Color(255, 255, 255));
        btndeletar.setText("Deletar");
        btndeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeletarActionPerformed(evt);
            }
        });
        getContentPane().add(btndeletar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 220, 230, 30));

        btnalterar.setBackground(new java.awt.Color(44, 148, 82));
        btnalterar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnalterar.setForeground(new java.awt.Color(255, 255, 255));
        btnalterar.setText("Alterar");
        btnalterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnalterarActionPerformed(evt);
            }
        });
        getContentPane().add(btnalterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, 230, 30));

        btnagendar.setBackground(new java.awt.Color(44, 148, 82));
        btnagendar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnagendar.setForeground(new java.awt.Color(255, 255, 255));
        btnagendar.setText("Cadastrar");
        btnagendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagendarActionPerformed(evt);
            }
        });
        getContentPane().add(btnagendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 120, 230, 30));

        lblpainel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imgBarb/imagens/Painel.png"))); // NOI18N
        getContentPane().add(lblpainel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 710, 410));

        lblfundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imgBarb/imagens/fundo.jpg"))); // NOI18N
        getContentPane().add(lblfundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 790, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUltimoActionPerformed
        controller.selecionarUltimo();
    }//GEN-LAST:event_BtnUltimoActionPerformed

    private void BtnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAnteriorActionPerformed
        controller.selecionarAnterior();
    }//GEN-LAST:event_BtnAnteriorActionPerformed

    private void BtnProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnProximoActionPerformed
        controller.selecionarProximo();
    }//GEN-LAST:event_BtnProximoActionPerformed

    private void BtnPrimeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPrimeiroActionPerformed
        controller.selecionarPrimeiro();
    }//GEN-LAST:event_BtnPrimeiroActionPerformed

    private void btndeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeletarActionPerformed
        controller.deletarProfissional();
    }//GEN-LAST:event_btndeletarActionPerformed

    private void btnalterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnalterarActionPerformed
        controller.atualizarProfissional();
    }//GEN-LAST:event_btnalterarActionPerformed

    private void btnagendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagendarActionPerformed
        controller.cadastrarProfissional();
    }//GEN-LAST:event_btnagendarActionPerformed

    private void TxtPesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtPesquisaKeyReleased
        String filtro = TxtPesquisa.getText();
        controller.pesquisarProfissional(filtro);
    }//GEN-LAST:event_TxtPesquisaKeyReleased

    private void TabelaProfissionaisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaProfissionaisMouseClicked
        controller.carregarRegistro();
    }//GEN-LAST:event_TabelaProfissionaisMouseClicked

    private void TxtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewProfissional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewProfissional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewProfissional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewProfissional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewProfissional().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAnterior;
    private javax.swing.JButton BtnPrimeiro;
    private javax.swing.JButton BtnProximo;
    private javax.swing.JButton BtnUltimo;
    private javax.swing.JTable TabelaProfissionais;
    private javax.swing.JTextField TxtCpf;
    private javax.swing.JTextField TxtEmail;
    private javax.swing.JTextField TxtId;
    private javax.swing.JTextField TxtNome;
    private javax.swing.JTextField TxtPesquisa;
    private javax.swing.JTextField TxtRg;
    private javax.swing.JTextField TxtTelefone;
    private javax.swing.JButton btnagendar;
    private javax.swing.JButton btnalterar;
    private javax.swing.JButton btndeletar;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblclientes;
    private javax.swing.JLabel lblcpf;
    private javax.swing.JLabel lblcpf1;
    private javax.swing.JLabel lblemail;
    private javax.swing.JLabel lblemail1;
    private javax.swing.JLabel lblfundo;
    private javax.swing.JLabel lblid;
    private javax.swing.JLabel lblnome;
    private javax.swing.JLabel lblpainel;
    private javax.swing.JLabel lbltelefone1;
    // End of variables declaration//GEN-END:variables

    public JTextField getTxtCpf() {
        return TxtCpf;
    }

    public void setTxtCpf(JTextField TxtCpf) {
        this.TxtCpf = TxtCpf;
    }

    public JTextField getTxtEmail() {
        return TxtEmail;
    }

    public void setTxtEmail(JTextField TxtEmail) {
        this.TxtEmail = TxtEmail;
    }

    public JTextField getTxtId() {
        return TxtId;
    }

    public void setTxtId(JTextField TxtId) {
        this.TxtId = TxtId;
    }

    public JTextField getTxtNome() {
        return TxtNome;
    }

    public void setTxtNome(JTextField TxtNome) {
        this.TxtNome = TxtNome;
    }

    public JTextField getTxtPesquisar() {
        return TxtPesquisa;
    }

    public void setTxtPesquisar(JTextField TxtPesquisar) {
        this.TxtPesquisa = TxtPesquisar;
    }

    public JTextField getTxtRg() {
        return TxtRg;
    }

    public void setTxtRg(JTextField TxtRg) {
        this.TxtRg = TxtRg;
    }

    public JTextField getTxtTelefone() {
        return TxtTelefone;
    }

    public void setTxtTelefone(JTextField TxtTelefone) {
        this.TxtTelefone = TxtTelefone;
    }

    public JTable getTabelaProfissionais() {
        return TabelaProfissionais;
    }

    public void setTabelaProfissionais(JTable TabelaProfissionais) {
        this.TabelaProfissionais = TabelaProfissionais;
    }

}
