/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.cadastro;

/**
 *
 * @author Tiago e Diogo
 */
public class viewCliente extends javax.swing.JFrame {

    /**
     * Creates new form viewCliente
     */
    public viewCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TextCod = new javax.swing.JTextField();
        lblid = new javax.swing.JLabel();
        textNome = new javax.swing.JTextField();
        lblnome = new javax.swing.JLabel();
        TextCpf = new javax.swing.JTextField();
        lblcpf = new javax.swing.JLabel();
        TextTelefone = new javax.swing.JTextField();
        lblemail = new javax.swing.JLabel();
        lblclientes = new javax.swing.JLabel();
        lbltelefone2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablecliente = new javax.swing.JTable();
        lbltelefone1 = new javax.swing.JLabel();
        lbltelefone3 = new javax.swing.JLabel();
        TextPesquisar = new javax.swing.JTextField();
        TextEmail = new javax.swing.JTextField();
        TextNascimento1 = new javax.swing.JTextField();
        btnnext = new javax.swing.JButton();
        tras = new javax.swing.JButton();
        frente = new javax.swing.JButton();
        btnreturn = new javax.swing.JButton();
        btndeletar = new javax.swing.JButton();
        btnalterar = new javax.swing.JButton();
        btnagendar = new javax.swing.JButton();
        lblpainel = new javax.swing.JLabel();
        lblfundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TextCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextCodActionPerformed(evt);
            }
        });
        getContentPane().add(TextCod, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 40, 22));

        lblid.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblid.setForeground(new java.awt.Color(204, 204, 204));
        lblid.setText("Cod");
        getContentPane().add(lblid, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, -1, -1));

        textNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNomeActionPerformed(evt);
            }
        });
        getContentPane().add(textNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 192, 22));

        lblnome.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblnome.setForeground(new java.awt.Color(204, 204, 204));
        lblnome.setText("Nome");
        getContentPane().add(lblnome, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, -1, -1));

        TextCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextCpfActionPerformed(evt);
            }
        });
        getContentPane().add(TextCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 192, 22));

        lblcpf.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblcpf.setForeground(new java.awt.Color(204, 204, 204));
        lblcpf.setText("CPF");
        getContentPane().add(lblcpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, -1, 20));

        TextTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextTelefoneActionPerformed(evt);
            }
        });
        getContentPane().add(TextTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 192, 22));

        lblemail.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblemail.setForeground(new java.awt.Color(204, 204, 204));
        lblemail.setText("Telefone");
        getContentPane().add(lblemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, -1, -1));

        lblclientes.setFont(new java.awt.Font("Arial", 1, 28)); // NOI18N
        lblclientes.setForeground(new java.awt.Color(204, 204, 204));
        lblclientes.setText("Clientes");
        getContentPane().add(lblclientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, -1, -1));

        lbltelefone2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbltelefone2.setForeground(new java.awt.Color(204, 204, 204));
        lbltelefone2.setText("Pesquisar Cliente:");
        getContentPane().add(lbltelefone2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, -1, 20));

        tablecliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nome", "CPF", "Nascimento", "Telefone", "Email"
            }
        ));
        jScrollPane2.setViewportView(tablecliente);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, 670, 120));

        lbltelefone1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbltelefone1.setForeground(new java.awt.Color(204, 204, 204));
        lbltelefone1.setText("Email");
        getContentPane().add(lbltelefone1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, -1, -1));

        lbltelefone3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbltelefone3.setForeground(new java.awt.Color(204, 204, 204));
        lbltelefone3.setText("Nascimento");
        getContentPane().add(lbltelefone3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, -1, -1));

        TextPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextPesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(TextPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, 270, 22));

        TextEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextEmailActionPerformed(evt);
            }
        });
        getContentPane().add(TextEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 192, 22));

        TextNascimento1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextNascimento1ActionPerformed(evt);
            }
        });
        getContentPane().add(TextNascimento1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 192, 22));

        btnnext.setBackground(new java.awt.Color(44, 148, 82));
        btnnext.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnnext.setForeground(new java.awt.Color(255, 255, 255));
        btnnext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imgBarb/icons/final.png"))); // NOI18N
        btnnext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnextActionPerformed(evt);
            }
        });
        getContentPane().add(btnnext, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 310, 30, 30));

        tras.setBackground(new java.awt.Color(44, 148, 82));
        tras.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tras.setForeground(new java.awt.Color(255, 255, 255));
        tras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imgBarb/icons/anterior.png"))); // NOI18N
        tras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trasActionPerformed(evt);
            }
        });
        getContentPane().add(tras, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 310, 30, 30));

        frente.setBackground(new java.awt.Color(44, 148, 82));
        frente.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        frente.setForeground(new java.awt.Color(255, 255, 255));
        frente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imgBarb/icons/proximo.png"))); // NOI18N
        frente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frenteActionPerformed(evt);
            }
        });
        getContentPane().add(frente, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 310, 30, 30));

        btnreturn.setBackground(new java.awt.Color(44, 148, 82));
        btnreturn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnreturn.setForeground(new java.awt.Color(255, 255, 255));
        btnreturn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imgBarb/icons/inicio.png"))); // NOI18N
        btnreturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreturnActionPerformed(evt);
            }
        });
        getContentPane().add(btnreturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 310, 30, 30));

        btndeletar.setBackground(new java.awt.Color(44, 148, 82));
        btndeletar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btndeletar.setForeground(new java.awt.Color(255, 255, 255));
        btndeletar.setText("Deletar");
        btndeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeletarActionPerformed(evt);
            }
        });
        getContentPane().add(btndeletar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 250, 230, 30));

        btnalterar.setBackground(new java.awt.Color(44, 148, 82));
        btnalterar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnalterar.setForeground(new java.awt.Color(255, 255, 255));
        btnalterar.setText("Alterar");
        btnalterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnalterarActionPerformed(evt);
            }
        });
        getContentPane().add(btnalterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 200, 230, 30));

        btnagendar.setBackground(new java.awt.Color(44, 148, 82));
        btnagendar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnagendar.setForeground(new java.awt.Color(255, 255, 255));
        btnagendar.setText("Cadastrar");
        btnagendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagendarActionPerformed(evt);
            }
        });
        getContentPane().add(btnagendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 150, 230, 30));

        lblpainel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imgBarb/imagens/Painel.png"))); // NOI18N
        getContentPane().add(lblpainel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 710, 410));

        lblfundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imgBarb/imagens/fundo.jpg"))); // NOI18N
        getContentPane().add(lblfundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 790, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextCodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextCodActionPerformed

    private void textNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNomeActionPerformed

    private void TextCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextCpfActionPerformed

    private void TextTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextTelefoneActionPerformed

    private void TextPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextPesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextPesquisarActionPerformed

    private void btnnextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnnextActionPerformed

    private void trasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_trasActionPerformed

    private void frenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_frenteActionPerformed

    private void btnreturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreturnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnreturnActionPerformed

    private void btndeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeletarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btndeletarActionPerformed

    private void btnalterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnalterarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnalterarActionPerformed

    private void btnagendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagendarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnagendarActionPerformed

    private void TextEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextEmailActionPerformed

    private void TextNascimento1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextNascimento1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextNascimento1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TextCod;
    private javax.swing.JTextField TextCpf;
    private javax.swing.JTextField TextEmail;
    private javax.swing.JTextField TextNascimento1;
    private javax.swing.JTextField TextPesquisar;
    private javax.swing.JTextField TextTelefone;
    private javax.swing.JButton btnagendar;
    private javax.swing.JButton btnalterar;
    private javax.swing.JButton btndeletar;
    private javax.swing.JButton btnnext;
    private javax.swing.JButton btnreturn;
    private javax.swing.JButton frente;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblclientes;
    private javax.swing.JLabel lblcpf;
    private javax.swing.JLabel lblemail;
    private javax.swing.JLabel lblfundo;
    private javax.swing.JLabel lblid;
    private javax.swing.JLabel lblnome;
    private javax.swing.JLabel lblpainel;
    private javax.swing.JLabel lbltelefone1;
    private javax.swing.JLabel lbltelefone2;
    private javax.swing.JLabel lbltelefone3;
    private javax.swing.JTable tablecliente;
    private javax.swing.JTextField textNome;
    private javax.swing.JButton tras;
    // End of variables declaration//GEN-END:variables
}
