/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.cadastro;

/**
 *
 * @author Tiago e Diogo
 */
public class viewAgendamento extends javax.swing.JFrame {

    /**
     * Creates new form viewAgendamento
     */
    public viewAgendamento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanelfundo = new javax.swing.JPanel();
        lblid = new javax.swing.JLabel();
        jtextid = new javax.swing.JTextField();
        lblnome = new javax.swing.JLabel();
        jtextnome = new javax.swing.JTextField();
        lbldata = new javax.swing.JLabel();
        jtextdata = new javax.swing.JTextField();
        lblvalor = new javax.swing.JLabel();
        jtextvalor = new javax.swing.JTextField();
        lblhora = new javax.swing.JLabel();
        jtexthora = new javax.swing.JTextField();
        lblservico = new javax.swing.JLabel();
        jcomboservico = new javax.swing.JComboBox<>();
        btnagendar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableagendamento = new javax.swing.JTable();
        lblagendamento = new javax.swing.JLabel();
        lblpainel = new javax.swing.JLabel();
        lblfundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpanelfundo.setBackground(new java.awt.Color(17, 17, 17));
        jpanelfundo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblid.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblid.setForeground(new java.awt.Color(204, 204, 204));
        lblid.setText("Id");
        jpanelfundo.add(lblid, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, -1));

        jtextid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtextidActionPerformed(evt);
            }
        });
        jpanelfundo.add(jtextid, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 192, -1));

        lblnome.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblnome.setForeground(new java.awt.Color(204, 204, 204));
        lblnome.setText("Nome");
        jpanelfundo.add(lblnome, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));

        jtextnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtextnomeActionPerformed(evt);
            }
        });
        jpanelfundo.add(jtextnome, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 192, -1));

        lbldata.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbldata.setForeground(new java.awt.Color(204, 204, 204));
        lbldata.setText("Data");
        jpanelfundo.add(lbldata, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, -1, -1));

        jtextdata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtextdataActionPerformed(evt);
            }
        });
        jpanelfundo.add(jtextdata, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 192, -1));

        lblvalor.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblvalor.setForeground(new java.awt.Color(204, 204, 204));
        lblvalor.setText("Valor");
        jpanelfundo.add(lblvalor, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, -1));

        jtextvalor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtextvalorActionPerformed(evt);
            }
        });
        jpanelfundo.add(jtextvalor, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 192, -1));

        lblhora.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblhora.setForeground(new java.awt.Color(204, 204, 204));
        lblhora.setText("Hora");
        jpanelfundo.add(lblhora, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, -1, -1));

        jtexthora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtexthoraActionPerformed(evt);
            }
        });
        jpanelfundo.add(jtexthora, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 192, -1));

        lblservico.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblservico.setForeground(new java.awt.Color(204, 204, 204));
        lblservico.setText("Serviço");
        jpanelfundo.add(lblservico, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        jcomboservico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Corte (Cabelo)", "Pintar Cabelo", "Penteado (Cabelo)", "Luzes (Cabelo)", "Hidratação (Cabelo)", "Aparar (Barba)", "Barba Completa (Barba)", "Barbaterapia (Barba)", "Aparar (Sombrancelha)" }));
        jcomboservico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcomboservicoActionPerformed(evt);
            }
        });
        jpanelfundo.add(jcomboservico, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 192, -1));

        btnagendar.setBackground(new java.awt.Color(44, 148, 82));
        btnagendar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnagendar.setForeground(new java.awt.Color(255, 255, 255));
        btnagendar.setText("Agendar");
        btnagendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagendarActionPerformed(evt);
            }
        });
        jpanelfundo.add(btnagendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, 230, 30));

        tableagendamento.setForeground(new java.awt.Color(204, 204, 204));
        tableagendamento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nome", "Serviço", "Valor", "Data", "Hora"
            }
        ));
        jScrollPane2.setViewportView(tableagendamento);

        jpanelfundo.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 670, 90));

        lblagendamento.setFont(new java.awt.Font("Arial", 1, 28)); // NOI18N
        lblagendamento.setForeground(new java.awt.Color(204, 204, 204));
        lblagendamento.setText("Agendamento");
        jpanelfundo.add(lblagendamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, -1, -1));

        lblpainel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imgBarb/imagens/Painel.png"))); // NOI18N
        jpanelfundo.add(lblpainel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 710, 320));

        lblfundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imgBarb/imagens/fundo.jpg"))); // NOI18N
        jpanelfundo.add(lblfundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 470));

        getContentPane().add(jpanelfundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnagendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagendarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnagendarActionPerformed

    private void jcomboservicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcomboservicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcomboservicoActionPerformed

    private void jtexthoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtexthoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtexthoraActionPerformed

    private void jtextvalorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextvalorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextvalorActionPerformed

    private void jtextdataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextdataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextdataActionPerformed

    private void jtextnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextnomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextnomeActionPerformed

    private void jtextidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextidActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewAgendamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewAgendamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewAgendamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewAgendamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewAgendamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnagendar;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> jcomboservico;
    private javax.swing.JPanel jpanelfundo;
    private javax.swing.JTextField jtextdata;
    private javax.swing.JTextField jtexthora;
    private javax.swing.JTextField jtextid;
    private javax.swing.JTextField jtextnome;
    private javax.swing.JTextField jtextvalor;
    private javax.swing.JLabel lblagendamento;
    private javax.swing.JLabel lbldata;
    private javax.swing.JLabel lblfundo;
    private javax.swing.JLabel lblhora;
    private javax.swing.JLabel lblid;
    private javax.swing.JLabel lblnome;
    private javax.swing.JLabel lblpainel;
    private javax.swing.JLabel lblservico;
    private javax.swing.JLabel lblvalor;
    private javax.swing.JTable tableagendamento;
    // End of variables declaration//GEN-END:variables
}
