/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.cadastro;

import controller.AgendamentoController;
import javax.swing.JComboBox;
import javax.swing.JTable;

/**
 *
 * @author Tiago e Diogo
 */
public class viewAgendamento extends javax.swing.JFrame {

    private final AgendamentoController controller;
    public viewAgendamento() {
        initComponents();
        controller = new AgendamentoController(this);
        inciar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TextData = new javax.swing.JTextField();
        lblid = new javax.swing.JLabel();
        lblnome = new javax.swing.JLabel();
        lblcpf = new javax.swing.JLabel();
        lbltelefone = new javax.swing.JLabel();
        lblemail = new javax.swing.JLabel();
        lblclientes = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaAgendamento = new javax.swing.JTable();
        CBCliente = new javax.swing.JComboBox<>();
        CBServico = new javax.swing.JComboBox<>();
        CBPagamento = new javax.swing.JComboBox<>();
        lbltelefone1 = new javax.swing.JLabel();
        BtnUltimo = new javax.swing.JButton();
        BtnAnterior = new javax.swing.JButton();
        BtnProximo = new javax.swing.JButton();
        BtnPrimeiro = new javax.swing.JButton();
        BtnDeletar = new javax.swing.JButton();
        BtnAlterar = new javax.swing.JButton();
        BtnCadastrar = new javax.swing.JButton();
        TextId1 = new javax.swing.JTextField();
        TextData1 = new javax.swing.JTextField();
        lblpainel = new javax.swing.JLabel();
        lblfundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TextData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextDataActionPerformed(evt);
            }
        });
        getContentPane().add(TextData, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, 190, 30));

        lblid.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblid.setForeground(new java.awt.Color(204, 204, 204));
        lblid.setText("Id");
        getContentPane().add(lblid, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 20, 10));

        lblnome.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblnome.setForeground(new java.awt.Color(204, 204, 204));
        lblnome.setText("Cliente");
        getContentPane().add(lblnome, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 60, 10));

        lblcpf.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblcpf.setForeground(new java.awt.Color(204, 204, 204));
        lblcpf.setText("Serviço");
        getContentPane().add(lblcpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 60, 10));

        lbltelefone.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbltelefone.setForeground(new java.awt.Color(204, 204, 204));
        lbltelefone.setText("Hora");
        getContentPane().add(lbltelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, -1, 10));

        lblemail.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblemail.setForeground(new java.awt.Color(204, 204, 204));
        lblemail.setText("Pagamento");
        getContentPane().add(lblemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 80, -1));

        lblclientes.setFont(new java.awt.Font("Arial", 1, 28)); // NOI18N
        lblclientes.setForeground(new java.awt.Color(204, 204, 204));
        lblclientes.setText("Agendamento");
        getContentPane().add(lblclientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, -1, -1));

        tabelaAgendamento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nome", "Serviço", "Pagamento", "Data", "Hora"
            }
        ));
        jScrollPane2.setViewportView(tabelaAgendamento);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, 670, 120));

        getContentPane().add(CBCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 190, 30));

        CBServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBServicoActionPerformed(evt);
            }
        });
        getContentPane().add(CBServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 190, 30));

        CBPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBPagamentoActionPerformed(evt);
            }
        });
        getContentPane().add(CBPagamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 190, 30));

        lbltelefone1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbltelefone1.setForeground(new java.awt.Color(204, 204, 204));
        lbltelefone1.setText("Data");
        getContentPane().add(lbltelefone1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, -1, 10));

        BtnUltimo.setBackground(new java.awt.Color(44, 148, 82));
        BtnUltimo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        BtnUltimo.setForeground(new java.awt.Color(255, 255, 255));
        BtnUltimo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imgBarb/icons/final.png"))); // NOI18N
        BtnUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUltimoActionPerformed(evt);
            }
        });
        getContentPane().add(BtnUltimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 300, 30, 30));

        BtnAnterior.setBackground(new java.awt.Color(44, 148, 82));
        BtnAnterior.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        BtnAnterior.setForeground(new java.awt.Color(255, 255, 255));
        BtnAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imgBarb/icons/anterior.png"))); // NOI18N
        BtnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAnteriorActionPerformed(evt);
            }
        });
        getContentPane().add(BtnAnterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 300, 30, 30));

        BtnProximo.setBackground(new java.awt.Color(44, 148, 82));
        BtnProximo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        BtnProximo.setForeground(new java.awt.Color(255, 255, 255));
        BtnProximo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imgBarb/icons/proximo.png"))); // NOI18N
        BtnProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnProximoActionPerformed(evt);
            }
        });
        getContentPane().add(BtnProximo, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 300, 30, 30));

        BtnPrimeiro.setBackground(new java.awt.Color(44, 148, 82));
        BtnPrimeiro.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        BtnPrimeiro.setForeground(new java.awt.Color(255, 255, 255));
        BtnPrimeiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imgBarb/icons/inicio.png"))); // NOI18N
        BtnPrimeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPrimeiroActionPerformed(evt);
            }
        });
        getContentPane().add(BtnPrimeiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 300, 30, 30));

        BtnDeletar.setBackground(new java.awt.Color(44, 148, 82));
        BtnDeletar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        BtnDeletar.setForeground(new java.awt.Color(255, 255, 255));
        BtnDeletar.setText("Deletar");
        BtnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDeletarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnDeletar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 240, 230, 30));

        BtnAlterar.setBackground(new java.awt.Color(44, 148, 82));
        BtnAlterar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        BtnAlterar.setForeground(new java.awt.Color(255, 255, 255));
        BtnAlterar.setText("Alterar");
        BtnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAlterarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 190, 230, 30));

        BtnCadastrar.setBackground(new java.awt.Color(44, 148, 82));
        BtnCadastrar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        BtnCadastrar.setForeground(new java.awt.Color(255, 255, 255));
        BtnCadastrar.setText("Cadastrar");
        BtnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCadastrar(evt);
            }
        });
        getContentPane().add(BtnCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 140, 230, 30));

        TextId1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextId1ActionPerformed(evt);
            }
        });
        getContentPane().add(TextId1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 40, 22));

        TextData1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextData1ActionPerformed(evt);
            }
        });
        getContentPane().add(TextData1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 190, 30));

        lblpainel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imgBarb/imagens/Painel.png"))); // NOI18N
        getContentPane().add(lblpainel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 710, 390));

        lblfundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imgBarb/imagens/fundo.jpg"))); // NOI18N
        getContentPane().add(lblfundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 790, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextDataActionPerformed

    private void BtnUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUltimoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnUltimoActionPerformed

    private void BtnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAnteriorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnAnteriorActionPerformed

    private void BtnProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnProximoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnProximoActionPerformed

    private void BtnPrimeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPrimeiroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnPrimeiroActionPerformed

    private void BtnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDeletarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnDeletarActionPerformed

    private void BtnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAlterarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnAlterarActionPerformed

    private void BtnCadastrar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCadastrar
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnCadastrar

    private void CBServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBServicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBServicoActionPerformed

    private void CBPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBPagamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBPagamentoActionPerformed

    private void TextId1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextId1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextId1ActionPerformed

    private void TextData1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextData1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextData1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewAgendamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewAgendamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewAgendamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewAgendamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewAgendamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAlterar;
    private javax.swing.JButton BtnAnterior;
    private javax.swing.JButton BtnCadastrar;
    private javax.swing.JButton BtnDeletar;
    private javax.swing.JButton BtnPrimeiro;
    private javax.swing.JButton BtnProximo;
    private javax.swing.JButton BtnUltimo;
    private javax.swing.JComboBox<String> CBCliente;
    private javax.swing.JComboBox<String> CBPagamento;
    private javax.swing.JComboBox<String> CBServico;
    private javax.swing.JTextField TextData;
    private javax.swing.JTextField TextData1;
    private javax.swing.JTextField TextId1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblclientes;
    private javax.swing.JLabel lblcpf;
    private javax.swing.JLabel lblemail;
    private javax.swing.JLabel lblfundo;
    private javax.swing.JLabel lblid;
    private javax.swing.JLabel lblnome;
    private javax.swing.JLabel lblpainel;
    private javax.swing.JLabel lbltelefone;
    private javax.swing.JLabel lbltelefone1;
    private javax.swing.JTable tabelaAgendamento;
    // End of variables declaration//GEN-END:variables

    private void inciar() {
        this.controller.atualizarTabela();
        this.controller.atualizarCliente();
        this.controller.atualizarServico();
        this.controller.atualizarPagamento();
    }

    public JTable getTabelaAgendamento() {
        return tabelaAgendamento;
    }
    
    public void setTabelaAgendamento(JTable tabelaAgendamento) {
        this.tabelaAgendamento = tabelaAgendamento;
    }

    public JComboBox<String> getCBCliente() {
        return CBCliente;
    }

    public void setCBCliente(JComboBox<String> CBCliente) {
        this.CBCliente = CBCliente;
    }

    public JComboBox<String> getCBPagamento() {
        return CBPagamento;
    }

    public void setCBPagamento(JComboBox<String> CBPagamento) {
        this.CBPagamento = CBPagamento;
    }

    public JComboBox<String> getCBServico() {
        return CBServico;
    }

    public void setCBServico(JComboBox<String> CBServico) {
        this.CBServico = CBServico;
    }
    
    
    
}
